### PR TITLE
Transfer CDK pipeline code from python to typescript

### PR DESCRIPTION
**Pull request by raylrui**
### CDK diff
The main difference primarily due to the different ways that the TypeScript CDK and the Python CDK handle certain resources and parameters. 
For detail difference 
[diff.txt](https://github.com/user-attachments/files/15572394/diff.txt)

Most difference are come from resource logical IDs and names changes and Role based difference.

### CODE REVIEW

**Comment by raylrui** [comment]
We may need do more test for this pipeline as the different ways that the TypeScript CDK and the Python CDK handle certain resources and parameters.

**Comment by victorskl** [comment]
.. will review in tick soon

**Comment by victorskl** [comment]
reviewing..

**Review by victorskl — APPROVED** [review]
Nicely done, Ray. 👍  Thank so much for migrating this.

Happy for you to take any necessary actions i.e. tear down the whole stack (as in with Python version of cdk) first. Then, re-spin the stack with newer TypeScript cdk code base.

While at it, will it also be possible to change the CI setup a bit. Such that, similar to orcabus i.e. CodePipeline CI in bastion account then CD deploy it into dev, stg, prod. If so, perhaps merge this first then pursuit it as another ticket task.

**Pull request merged**
