### PR TITLE
Change API Query Params

### PR DESCRIPTION
**Pull request by williamputraintan**
Refactor Query Params, to follow with portal API change. Only these 2 commits was affected from the last dev -> main branch merge:

- af62ed5621d12576653078e2ed139c557a6e003f
- 129dfc9809a31d51a0b2e9e295fb19f6cc1e26aa

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
Just reviewed the mentioned 2 commits from comment, which is LGTM. 

I takes others are for release merging, yes? I'd recommend `main <- dev` Release PR as separate PR in future to emphasise the distinction... which will be less about review but more on release trigger control and final check... etc

**Review by reisingerf — APPROVED** [review]

**Comment by reisingerf** [comment]
Agree with Victor, we may need to improve our PR/merge strategy....
Why do all those old commits show up in the PR? I thought it would just pick up from the last merge?
How do we do that on the portal? Development on separate branches, then PR (feature/issue based) against `dev` for testing, and finally PR those (from `dev`) against `main` for production release?

**Review by victorskl — COMMENTED** [review]
> How do we do that on the portal? Development on separate branches, then PR (feature/issue based) against dev for testing, and finally PR those (from dev) against main for production release?

Yes @reisingerf 

This flow is for, if there exists two long running branches that backing deployed app environment... It looks [like this](https://github.com/umccr/data-portal-apis/pull/371). With milestone view, it reflects [work summary](https://github.com/umccr/data-portal-apis/milestone/4?closed=1).

For library component and single branch, you can have dedicated Release branch and keep it there after merged (i.e. do not delete it). Like [this](https://github.com/umccr/libumccr/pull/9) and [this](https://github.com/umccr-illumina/libica/pull/53), for example...

**Comment by victorskl** [comment]
... and git tag!

**Pull request merged**
